@baseUrl = http://localhost:3000/api/courses
@instructorToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1YWM0OWViLWJiMmMtNDMyZS1iMDk0LTMyZjFkYTZkYmYzNiIsImVtYWlsIjoiZWFybGpvZTA2QG91dGxvb2suY29tIiwicGhvbmVOdW1iZXIiOiIwNzExMjI0NTg1MyIsInJvbGUiOiJJTlNUUlVDVE9SIiwiaWF0IjoxNzM4NTg2MTQwLCJleHAiOjE3Mzg1ODk3NDB9.YqBbSLAFowFmIL1kPT-5rlfyJSQmjnNph4uV5jaUmVE
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ2ODgwZjkzLWMzYTUtNGZmNC04YjJjLTE1MDljMDEzNmE1MiIsImVtYWlsIjoiZWFybGpvZTA2QGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcxMTIyNzIyNTAiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MzgzMzQyMTcsImV4cCI6MTczODMzNzgxN30.3w3mPN06i2IOU_O-m1XcQrXXrk4_3ToARkeWo8Kl8ik
@studentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5YjdhZGVjLTJkNjktNDJiMS05ODc2LTQ0MmRlNzZhOGNlNSIsImVtYWlsIjoicmlnaHRtZW5jdXN0b216QGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IkRvZSIsInBob25lTnVtYmVyIjoiMDEwNjMyNjYyNyIsInJvbGUiOiJMRUFSTkVSIiwiaWF0IjoxNzQxNzI0OTg4LCJleHAiOjE3NDE3Mjg1ODh9.zvuMRGXujczSVDQl4nhzScVM4jD-pkbsWbQpQddNk4M

### Auth Setup ###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "earljoe06@gmail.com",
    "password": "password"
}

### INSTRUCTOR TOKEN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "earljoe06@outlook.com",
    "password": "password"
}

### STUDENT TOKEN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "rightmencustomz@gmail.com",
    "password": "password"
}


### Public Routes ###

### List all courses
GET {{baseUrl}}

### Get course by ID
GET {{baseUrl}}/e69bc7b7-1eb6-4cc0-b41f-94989ae1f7df
Authorization: Bearer {{studentToken}}

### Get courses by category
GET {{baseUrl}}/category/90b68f2c-e759-4e70-8034-396b7565ad74
Authorization: Bearer {{studentToken}}

### Get instructor's courses
GET {{baseUrl}}/instructor/d5ac49eb-bb2c-432e-b094-32f1da6dbf36
Authorization: Bearer {{studentToken}}

### Student Routes ###


###GET ENROLLMENT FOR A USER
GET {{baseUrl}}/u/enrollments
Authorization: Bearer {{studentToken}}

### Enroll in course
POST {{baseUrl}}/92976e55-7da0-4e6a-a2b6-ae4bf8865446/enroll
Authorization: Bearer {{studentToken}}
Content-Type: application/json

{
    "paymentMethod": "MPESA"
}

### Defer to different cohort
POST {{baseUrl}}/cohorts/2b652a2b-6b7a-4a18-ba3f-fda3d2eb2cdb/defer/251a78cc-0767-4921-ba44-adcc1025ca2e
Authorization: Bearer {{studentToken}}

### Instructor Routes ###

### Create course with banner
POST {{baseUrl}}
Authorization: Bearer {{instructorToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
 
------WebKitFormBoundary
Content-Disposition: form-data; name="title"

Introduction To JavaScript
------WebKitFormBoundary
Content-Disposition: form-data; name="description"

Get started with our comprehensive introduction to JavaScript programming
------WebKitFormBoundary
Content-Disposition: form-data; name="isPaid"

false
------WebKitFormBoundary
Content-Disposition: form-data; name="categoryIds"

["90b68f2c-e759-4e70-8034-396b7565ad74"]

------WebKitFormBoundary
Content-Disposition: form-data; name="subCategoryIds"

["7753f1b7-1f11-4671-ad9e-6b16cd757f67", "2b02ace0-6c78-4306-9de8-5ce25bd1c791"]

------WebKitFormBoundary
Content-Disposition: form-data; name="bannerImage"; filename="banner.jpg"
Content-Type: image/jpeg

< /home/earljoe/Downloads/JavaScript-Introduction.jpg
------WebKitFormBoundary--

### Update course
PUT {{baseUrl}}/e69bc7b7-1eb6-4cc0-b41f-94989ae1f7df
Authorization: Bearer {{instructorToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
 
------WebKitFormBoundary
Content-Disposition: form-data; name="title"

Software Testing and Automation 1 (Cypress)
------WebKitFormBoundary
Content-Disposition: form-data; name="description"

Deep dive into Cypress Testing Framework
------WebKitFormBoundary
Content-Disposition: form-data; name="isPaid"

true
------WebKitFormBoundary
Content-Disposition: form-data; name="price"

5000
------WebKitFormBoundary--

### Delete course
DELETE {{baseUrl}}/e69bc7b7-1eb6-4cc0-b41f-94989ae1f7df
Authorization: Bearer {{instructorToken}}

### Publish/Unpublish course
POST {{baseUrl}}/92976e55-7da0-4e6a-a2b6-ae4bf8865446/publish
Authorization: Bearer {{instructorToken}}
Content-Type: application/json

{
    "publish": true
}

### Cohort Management ###

### Create cohort
POST {{baseUrl}}/92976e55-7da0-4e6a-a2b6-ae4bf8865446/cohorts
Authorization: Bearer {{instructorToken}}
Content-Type: application/json

{
    "startDate": "2025-02-02T00:00:00Z"
}

### List course cohorts
GET {{baseUrl}}/92976e55-7da0-4e6a-a2b6-ae4bf8865446/cohorts
Authorization: Bearer {{instructorToken}}

### Student Management ###

### List enrolled students
GET {{baseUrl}}/92976e55-7da0-4e6a-a2b6-ae4bf8865446/students
Authorization: Bearer {{instructorToken}}

